#! /bin/bash

# This hook runs BEFORE the devcontainer files are copied and user-specific
# env settings are appended. Note that non-user specific env. is available here

# Use this hook to check dependencies or other tasks like generating files used
# by other hooks or the devcontainer itself

echo "Pre-activate hook for template: $DEVCONTAINER_NAME running in $PWD"