#! /bin/bash

# This hook runs BEFORE the template is copied to ./.devcontainer/$DEVCONTAINER_NAME
# Use this to check any host dependencies required by (other hooks in) the template
# Returning a non-zero error code will abort initialization

echo "Pre-initialize hook for template: $DEVCONTAINER_NAME running in $PWD"