#! /bin/bash

# This hook runs AFTER the devcontainer files have been copied and user-specific
# env settings appended.

echo "Post activate hook for template: $DEVCONTAINER_NAME running in $PWD"

# Run any host setup commands here 
# Ex: docker-machine env, docker buildx, xhost, modprobe, etc.
echo "Host setup goes here"

# Launch shell/development environment here
# Ensure that the command you provide does not return before the 
# editor/shell has exited, or cleanup will take place too early

# Here's how to launch Visual Studio Code in a new window
# with current env and wait till it's closed

# code --wait --new-window --folder-uri $PWD
echo "Start our development/build environment here"

# Run host cleanup stuff here after our editor has shut down
# ex: docker machine env -u, unset modprobe -r, etc.
echo "Host cleanup goes here"